USE [ALMS]
GO

/****** Object:  Table [dbo].[TR01X]    Script Date: 2018/7/20 ¤U¤È 09:40:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TR01X](
	[TR01X_ID] [int] IDENTITY(1,1) NOT NULL,
	[TRN_DT] [varchar](8) NOT NULL,
	[ACC_NO] [varchar](8) NOT NULL,
	[DEB_MY] [decimal](20,4) NULL,
	[CRE_MY] [decimal](20,4) NULL,
	[CREATE_USER] [varchar](30) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[ACT_YN] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[TR01X_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


