//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALMSEntities : DbContext
    {
        public ALMSEntities()
            : base("name=ALMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BA01A> BA01A { get; set; }
        public virtual DbSet<BA02A> BA02A { get; set; }
        public virtual DbSet<BA02B> BA02B { get; set; }
        public virtual DbSet<BA03A> BA03A { get; set; }
        public virtual DbSet<BA04A> BA04A { get; set; }
        public virtual DbSet<DA01A> DA01A { get; set; }
        public virtual DbSet<DA02A> DA02A { get; set; }
    }
}
