//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA01A
    {
        public int BA01A_ID { get; set; }
        public string ACC_NO { get; set; }
        public string ACC_NM { get; set; }
        public Nullable<int> LEV_QT { get; set; }
        public Nullable<int> DA01A_ID { get; set; }
        public string SMO_YN { get; set; }
        public Nullable<int> DA02A_ID { get; set; }
        public string DEP_YN { get; set; }
        public string OBJ_YN { get; set; }
        public string DAT_YN { get; set; }
        public string PRJ_YN { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
