//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA02B
    {
        public int BA02B_ID { get; set; }
        public int BA02A_ID { get; set; }
        public string CUS_NO { get; set; }
        public string CUS_NM { get; set; }
        public string TEL_NO { get; set; }
        public string HND_NO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ACT_YN { get; set; }
    }
}
