//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR01A
    {
        public int TR01A_ID { get; set; }
        public string TRN_DT { get; set; }
        public Nullable<int> DA03A_ID { get; set; }
        public string VOU_NO { get; set; }
        public Nullable<int> BA02A_ID { get; set; }
        public Nullable<int> BA02B_ID { get; set; }
        public Nullable<int> BA03A_ID { get; set; }
        public Nullable<int> BA01A_ID { get; set; }
        public string SUM_RM { get; set; }
        public Nullable<decimal> DEB_MY { get; set; }
        public Nullable<decimal> CRE_MY { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ACT_YN { get; set; }
    }
}
